Repository wieslawsoltes/wmf, pull requests merged in 2023-04, with the labels that each got.

#1 DeviceIndependentBitmap: read color data
  library/Objects/DeviceIndependentBitmap.cs
Labels: size/XS

#5 Add build system
  .nuke/build.schema.json
  .nuke/parameters.json
  azure-pipelines.yml
  build.cmd
  build.ps1
  build.sh
  build/build/Build.cs
  build/build/_build.csproj
  wmf.sln
Labels: size/L

#4 Docs: reword README, fix a spec link
  README.md
Labels: size/XS

#6 Add GitHub Actions
  .github/workflows/build.yml
Labels: size/S

#7 Add badges to Readme
  README.md
Labels: size/S

#8 Update to .NET 7
  build/build/_build.csproj
  global.json
  samples/sample/Console.csproj
  src/library/Library.csproj
  tests/library.UnitTests/library.UnitTests.csproj
Labels: size/S
